language: rust
os:
- windows
- linux
sudo: false
cache: cargo
script:
- cargo build --release --verbose --all
- cargo test --verbose --all
deploy:
  provider: releases
  api_key:
    secure: llBry9SnihCFL/aKP1ODeh6VmfFVzOYage5T5/x6dLBHzmdx1Png5SdNG1xAy/4xQRX569DkCfKvA89OVv5jte9kGR0ZnImvxxuI+y2kWRVWRUjaEoDuvmRoZwx1tGwHzgKpfbHpBwJxTjdwxvu0pmz812iHIUS6XdXR1B/gVky0RQ6pU8YPxnZfdG1IWGU/JaaLZRtMKuE1gui3XYtGepX4ZB2zU2WqmJNn/H+UHVPv4b3yehD0O9Ep7dMfgAtIQDg7WpiXhVe9sL5ESFvWIGvnAEgz/cgnP3C5pgi8H/4QGTjHfixpv1HGl73HHB4pAFqCw+Ky6B6Z3qKYQCt/Vwvfqt4JXuOKudOYI7DlxYjOmb2ARVcAy6vk8TxdVS/HZIN1k+kR8EXlsGAAriIOIMrdK5WP9P5I/rI+6tnaWI9HPTPgFLTgAl4uWTzzLNpepDXT7XnygZ9f97u5V7Llbe0ny8rpSfViI6MG2c8FTd1IhIAADxrIFAS9/Ehl4LKqDjoiTJLA2aEycYEqq99rHm+EixkzlRL3wD0TupR9Kp69TxXp+Y1pdNRsajyzEKlwemm+vUX7kBVgo4O2qwrMjimqpZz0eYzxSIm7eI8s8nj+xcbO5li3pgamb43JDJtXKOQKwzDXZYBPmXgDDF2PVANGmyh6GMcIiYwY2OSpqik=
  file:
  - target/release/csl_to_md
  - target/release/csl_to_md.exe
  on:
      tags: true
    repo: Eonm/csl-to-markdown
