language: rust
os:
- windows
- linux
sudo: false
cache: cargo
script:
- cargo build --release --verbose --all
- cargo test --verbose --all
deploy:
  provider: releases
  api_key:
    secure: "kHAXGS6D74zx5Mz7TyvsklzZuA7e7UDG/0qjYhGR/4h8c++SQsff2DzKqJusFi2M0Je4m8rx1mMSubEjoaDVnUJGFAwqsKNCt+6LdU0GYHnveMy+R7PgB6+aGEjuNkJkxU/YmzFcEG+0Squi7rt8ha3MZ1DuKFfbirKdbcCMkQZIjcntJhca1EwXIH7+n62hyusw/fD1Elt6r50q0l2yu4IFlKG/J8i+Z5voj0IdhrQ+5Ri3gNZpOeh5samtgjYVdcsMYHYrLEUOVPrh7lln5wLRzfU4WAJfRg+UEsKVHFPfMrCasE/DcNfTR4WNSP8rF4yikuD33Gw3Ly6BbTSOxn/peykXG2wB0WSOUKG9Wfr7l4AKYMqemdHvPvdyLhC+BXzXKu6BsN/q43rKwJePybFjdtMIfAFaWKCmNbOSYhSQ0atcoGQb+ki0OupjsFVmHEel+MrOetGBYXyTCqaUKraENmOOJ9GEWPPdSLC/DnfPvZi4wmF9VvulmQ+vCEafSuI013GLwg7uxTBYof2PRjdkql/UvtEFy2nka3drgDmrn2LSvhfCM4rSO2FkGP5o4FvFiJcSGYiNmdf7ldPAt3TSalu6qXah1XoHd9Q6S1NT5aNAgPm0Rqko22sGv+xijWn1fp8fjpm6XdlIhbYrITmOadDcwE3RHQs1aBkAMYE="
  file:
  - target/release/csl_to_md
  - target/release/csl_to_md.exe
  skip_cleanup: true
  on:
    repo: Eonm/csl-to-markdown
    tags: true
